@startuml
actor User


ref over ShowWindow, Handler: GUI::OpenWindow()
activate ShowWindow
activate ShowWindow #aaff00

activate Handler
activate Handler #aaff00

User -> ShowWindow : Enter teacher's name and surname
ShowWindow --> User : Show Dialog :\nconfirmation
ShowWindow -> Handler : Data entered\nsend data
alt declining
ShowWindow --> User: Back to Window
end
ref over Handler : Base::DelSchedule();
alt invalid data
Handler --> ShowWindow : Return fail
destroy Handler
ShowWindow --> User : Show Dialog :\nInvalid name or surname
destroy ShowWindow
end

Handler --> ShowWindow : Return success\nmessage
destroy Handler
ShowWindow -> ShowWindow : Show Data
ShowWindow --> User : Success message shown
destroy ShowWindow
@enduml